server.port=1234

# JSP View Configuration
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

# MySQL ko hata kar H2 Database connect kiya hai (No Server Needed) - File-Based Configuration
spring.datasource.url=jdbc:h2:file:./data/bankdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=username
spring.datasource.password=password

# H2 Console enable karne ke liye (Browser me data dekhne ke liye, [ jdbc URL : jdbc:h2:file:./data/bankdb + username + password ])
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate & JPA Settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# H2 ke liye sahi database platform/dialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
